server:
  port: 8081

spring:
  application:
    name: spring-webflux-nosql
  data:
    mongodb:
      database: vallegrande_db
      uri: mongodb+srv://anthonygala_db_user:Iftk7ycgTDct6dSG@cluster0.k3yvbp8.mongodb.net/vallegrande_db?retryWrites=true&w=majority

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html